apiVersion: v1
kind: Service
metadata:
  name: meanjsapp-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: meanjsapp-port
    protocol: TCP
  selector:
    app: meanjsapp
  type: NodePort
